<?php

use Illuminate\Database\Seeder;


class PaisesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table("paises")->delete();
        DB::table('paises')->insert(Array('pais' => 'Afganistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Gland','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Albania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Alemania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Andorra','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Angola','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Anguilla','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Antártida','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Antigua y Barbuda','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Antillas Holandesas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Arabia Saudí','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Argelia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Argentina','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Armenia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Aruba','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Australia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Austria','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Azerbaiyán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bahamas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bahréin','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bangladesh','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Barbados','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bielorrusia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bélgica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Belice','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Benin','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bermudas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bhután','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bolivia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bosnia y Herzegovina','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Botsuana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Isla Bouvet','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Brasil','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Brunéi','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Bulgaria','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Burkina Faso','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Burundi','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Cabo Verde','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Caimán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Camboya','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Camerún','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Canadá','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'República Centroafricana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Chad','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'República Checa','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Chile','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'China','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Chipre','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Isla de Navidad','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Ciudad del Vaticano','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Cocos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Colombia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Comoras','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'República Democrática del Congo','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Congo','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Cook','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Corea del Norte','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Corea del Sur','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Costa de Marfil','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Costa Rica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Croacia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Cuba','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Dinamarca','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Dominica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'República Dominicana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Ecuador','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Egipto','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'El Salvador','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Emiratos Árabes Unidos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Eritrea','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Eslovaquia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Eslovenia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'España'));
        DB::table('paises')->insert(Array('pais' => 'Islas ultramarinas de Estados Unidos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Estados Unidos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Estonia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Etiopía','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Feroe','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Filipinas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Finlandia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Fiyi','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Francia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Gabón','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Gambia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Georgia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Georgias del Sur y Sandwich del Sur','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Ghana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Gibraltar','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Granada','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Grecia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Groenlandia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guadalupe','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guam','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guatemala','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guayana Francesa','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guinea','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guinea Ecuatorial','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guinea-Bissau','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Guyana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Haití','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Heard y McDonald','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Honduras','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Hong Kong','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Hungría','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'India','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Indonesia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Irán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Iraq','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Irlanda','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islandia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Israel','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Italia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Jamaica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Japón','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Jordania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Kazajstán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Kenia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Kirguistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Kiribati','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Kuwait','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Laos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Lesotho','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Letonia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Líbano','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Liberia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Libia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Liechtenstein','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Lituania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Luxemburgo','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Macao','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'ARY Macedonia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Madagascar','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Malasia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Malawi','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Maldivas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Malí','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Malta','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Malvinas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Marianas del Norte','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Marruecos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Marshall','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Martinica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mauricio','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mauritania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mayotte','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'México','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Micronesia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Moldavia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mónaco','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mongolia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Montserrat','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Mozambique','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Myanmar','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Namibia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nauru','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nepal','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nicaragua','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Níger','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nigeria','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Niue','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Isla Norfolk','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Noruega','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nueva Caledonia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Nueva Zelanda','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Omán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Países Bajos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Pakistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Palau','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Palestina','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Panamá','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Papúa Nueva Guinea','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Paraguay','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Perú','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Pitcairn','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Polinesia Francesa','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Polonia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Portugal','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Puerto Rico','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Qatar','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Reino Unido','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Reunión','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Ruanda','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Rumania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Rusia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Sahara Occidental','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Salomón','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Samoa','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Samoa Americana','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'San Cristóbal y Nevis','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'San Marino','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'San Pedro y Miquelón','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'San Vicente y las Granadinas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Santa Helena','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Santa Lucía','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Santo Tomé y Príncipe','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Senegal','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Serbia y Montenegro','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Seychelles','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Sierra Leona','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Singapur','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Siria','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Somalia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Sri Lanka','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Suazilandia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Sudáfrica','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Sudán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Suecia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Suiza','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Surinam','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Svalbard y Jan Mayen','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tailandia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Taiwán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tanzania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tayikistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Territorio Británico del Océano Índico','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Territorios Australes Franceses','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Timor Oriental','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Togo','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tokelau','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tonga','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Trinidad y Tobago','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Túnez','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Turcas y Caicos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Turkmenistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Turquía','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Tuvalu','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Ucrania','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Uganda','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Uruguay','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Uzbekistán','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Vanuatu','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Venezuela','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Vietnam','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Vírgenes Británicas','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Islas Vírgenes de los Estados Unidos','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Wallis y Futuna','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Yemen','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Yibuti','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Zambia','activo'=>false));
        DB::table('paises')->insert(Array('pais' => 'Zimbabue','activo'=>false));
    }
}